{% set pkgname = "pv" %}
{% set version = "1.6.20" %}
{% set sha256 = "e831951eff0718fba9b1ef286128773b9d0e723e1fbfae88d5a3188814fdc603" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.bz2
  url: http://www.ivarch.com/programs/sources/{{ pkgname }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - pv --version

about:
  home: http://www.ivarch.com/programs/pv.shtml
  license: Artistic-2.0
  summary: pv - monitor the progress of data through a pipe

extra:
  recipe-maintainers:
    - shahin
