{% set pkgname = "pv" %}
{% set version = "1.7.0" %}
{% set sha256 = "1372b41053881a05e2df10cb054304decc0233261c0aa0e96185842fa5a422ad" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.bz2
  url: http://www.ivarch.com/programs/sources/{{ pkgname }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - make
    - {{ compiler('c') }}

test:
  commands:
    - pv --version

about:
  home: http://www.ivarch.com/programs/pv.shtml
  license: Artistic-2.0
  summary: pv - monitor the progress of data through a pipe

extra:
  recipe-maintainers:
    - shahin
