travis:
  secure:
    BINSTAR_TOKEN: tJPaIW0yrSYb7xpeNESjuKhoJyUa2YydtyR5ZuVk2Zp71DecwjIzyDYbeaZC+JNZtKT6+ARu8NFp655NBPp+XUfF6ITW48Jst1gsWmw0IYgDeAPYzxoq690Rxj+OVhMuy8WnKkEVAn2HtgG+CVlHZhaaGPMROrT6Jf52y4SwYhr0rkC/uZVo+pTnZaKAW/AGG2eiJ5Fu1Ngl3fYOepm62fElGCqHUEuRvSZaDf81m6svl3i5FD0fm5QgNLj/exC6Je0Nwhqkf3LAq2hNuje8odViCVrDO53VHpTfWJ3yD3QA5WSopu78gdRl6rKD/WPDuKZg7/Sy6+gJRN/sxuigpqtVU4B80mh3FKEL2lc9aFzF0gYaUYWDygUf+rRTO8WzSmrpbBQhPDYdF4vcMcYji5WcEB3ogNJpIkob0BtEF8aElowg0qByx82k4LO63JK5ue63mpKOFzskJ+/Il3HQaaVKv857jDNCunT/7gsdzsYERwIDz0wtfuuQ260aQT5z4OV4zzLBM2reYvlaXdmiufHKlWn8zx1pv1yuSJkAN9BlRPLCjVuNSsyqkaZ0S4uWG64qLr+sAvuA5Gf0R07tlx2vPy+eQAj6jLImrRdMEwAxMP/PRtVIV58Vd1Dl6l+03ybmit7nbGEvSax7ANwbW+OYGPSMjJErTs3y57595xg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
